### PR TITLE
Multiple Entry Points

### LINKED ISSUE #17: Make compilation to js optional + native compilation
It would be great if there was a way to let the user decide if compilation to js should happen or not.
This could be done with a flag in package.json or `./node_modules/.bin/compile --jsoo` for example.

While checking the source I found that everything gets compiled to bytecode with `ocamlc`.
Maybe we should extend the above to also let the user decide if he wants to target native with `ocamlopt`.

### LINKED ISSUE #36: Have an entry point, and only compile the transitive dependencies of that file
I have 3 binary targets, and 2 bucklescript targets in my `myntax` project, and rebel just wants to bundle everything up as one, which causes a ton of problems.
Currently, source files are discovered just by globbing the `src` directory, but if an `entry` is specified in the rebel package.json config, then _only_ that file and its dependencies should be processed.

### PR DESCRIPTION
**Pull request by vramana**
- [x] Backends
- [x] Merlin
- [x] Refactor + comments

Fixes #36 
Fixes #17

### CODE REVIEW

**Comment by jordwalke** [comment]
I'd love to hear more about what this change does (I'm not a Jenga expert)

**Comment by vramana** [comment]
This is the one of the two steps that will enable multiple entry points.

Currently, we don't track third party dependencies via the source files. We just read them from package.json and assume that they are being used. So we compile all dependencies regardless of whether they are necessary or not and include their artifacts while compiling and liniking. These assumptions worked okay till now because we are only dealing with one compiler. But when we have multiple entry points, some dependency may not be compiled by `bsc` or `ocamlc`. So, we compute ocamldep for each file and gather all the npm dependencies & ocamlfind dependencies and selectively compile them/include them while compiling/linking the source files. So, unused dependency will not be compiled will not compiled after this change. That is the gist of the PR. 

I have made one subtle assumption temporarily. I assume that packages have not declared any extra dependencies that they have not used. Is this an okay assumption? I guess you can't.

**Comment by jordwalke** [comment]
> I have made one subtle assumption temporarily. I assume that packages have not declared any extra dependencies that they have not used.

But you just said:

> So, unused dependency will not be compiled will not compiled after this change. 

And does this change track _which_ files in my packages dependencies I use, or just the mere fact that I _use_ the dependency in general?

**Comment by vramana** [comment]
Sorry for the confusing statement. We don't any compile unused packages from your source and dependencies as well. In the next step, we want to link whatever have been compiled so far but this is different function we need to recompute the dependencies all over again for your source and dependencies. 

We can skip some of the computation here by assuming that packages don't over specify dependencies. And that's what I did in this PR. I know this feels very inconsistent. I'll change the code to just recompute everything.

**Pull request merged**
