### PR TITLE
Add ppxFlag support.

### PR DESCRIPTION
**Pull request by bsansouci**
Adds the possibility to do

```
{
  "jengaboot": {
    "ppxFlag": "..."
  }
}
```

### CODE REVIEW

**Comment by chenglou** [comment]
How do ppx flags work? Which libraries should you specify?

**Comment by bsansouci** [comment]
This is the best example of its usage: https://github.com/bsansouci/core_kernel/blob/master/package.json#L14

I think you should be able to just install `ppx_jane` from opam. I'm hoping to get that sandboxed too at some point, so we don't have to rely on opam. I did some work in compiling each preprocessor using jengaboot itself but ran into the problem that the preprocessors are both a library and an executable. Jengaboot doesn't really have a story for exporting those two right now and it'll take a whole bunch of work that might not be needed right now.

**Comment by chenglou** [comment]
Jengaboot needs a story for exporting what? Can you be more specific? If it's a frequent use-case we should probably support it.

**Comment by bsansouci** [comment]
Jengaboot might need a story for exporting both an executable and a library. In the case of ppx, the preprocessors need to be built as executables (so they can be given to the compiler toolchain) but they also need to expose a runtime such that the user's code can access it.
Writing this I realize that we'd probably make a special case for preprocessors, because jengaboot would not only need to know how to compile it down to an executable but it would need to know to use it as a preprocessor (maybe?)

**Comment by chenglou** [comment]
Isn't the executable just the binary output? BetterErrors just takes it and publishes it. Doesn't work well because of some unrelated quirks though.

**Comment by bsansouci** [comment]
If we can actually just pre-build it and publish it, then that does solve it. A user could point their ppxFlag to `node_modules/.bin/ppx_XYZ`. Did you figure out how to not have a hardcoded absolute path in the byte code?

**Comment by bsansouci** [comment]
Whoops ignore this.

**Comment by chenglou** [comment]
noooooo

**Comment by bsansouci** [comment]
Sorry, I might've erased history :/
The other PR's more important lol

**Pull request closed without merging**
